### ISSUE TITLE
Installing VIPM package to LabVIEW 64-bit results in broken VIM wires

### ISSUE THREAD

**Issue by dataflowg** [dataflowg/g-audio#12]
Broken VIM wires, yet again.

The VIPM package is built with LabVIEW 32-bit, and includes the G-Audio lvlib and example VIs. When this package is installed to LabVIEW 64-bit, any VIs which call VIMs containing a CLFN will be broken. A quickdrop + replace of the offending VIM with the same VIM, followed by a ctrl+run arrow is enough to fix things. Interestingly if the G-Audio project is opened in LabVIEW 64-bit, everything is fine.

Suspect the broken wires are a result of stale malleable VI instances still pointing to 32-bit CLFN calls, a product of the VIPM build process. The VIPM build process does change CLFN paths (replacing `g_audio_*.*` with `g_audio_32.dll`). To remedy this, there's a post install VI which reverts the path change for all installed files, but it doesn't cover the malleable VI instances within VIs.

Proposed fix is to scan through all VIs and either replace VIMs, or update CLFN paths within VIM instances.

(I suspect VIPM's *Do Not Compile on Build* option would also fix this issue, but it requires a Community or Pro activation, and it won't let me sign in with error *LabVIEW: (Hex 0x58BF3) LabVIEW could not verify the authenticity of the server.*)

**Comment by jimkring** [comment]
Oh, geez. Please [email the VIPM support team](https://support.vipm.io/hc/en-us/requests/new) and we'll get you activated.

Also want to figure out how to solve this bug...

**Comment by dataflowg** [comment]
Thanks, I'll email support when I get a chance.

I've got a quick and dirty solution working, which involves performing the initial CLFN path update based on the code example you [posted here](https://forums.vipm.io/topic/2427-call-library-function-node-32-and-64-bit/#comment-8609). Once al the CLFN paths are updated and VIs saved, each VI is then checked for subVIs which are vims (using the subVI's label text and not the name or path, as that's just the instance GUID). If a vim is found, the Replace method of the subVI reference is called and the path set to the original vim.

**Comment by dataflowg** [comment]
@jimkring I couldn't send a support request (no VIPM Pro key), but have posted about the login issue in the [thread here](https://forums.vipm.io/topic/3306-login-fails/?do=findComment&comment=10106).

I've also posted the edited version of the post installation VI to [this thread](https://forums.vipm.io/topic/2427-call-library-function-node-32-and-64-bit/?do=findComment&comment=10107). It works for this project, though is a little slow to execute (~2 minutes across 160 VIs).
