### ISSUE TITLE
Feature Request: set audio device volume

### ISSUE THREAD

**Issue by Ryan-fuli** [dataflowg/g-audio#13]
Is there a interface to set volume in G Audio? what I ask for is something like "Sound output set volume.vi", thanks!
![sound vi](https://user-images.githubusercontent.com/80661060/172545033-d2febb79-196b-4903-be4b-13eee1caebbd.png)

**Comment by Ryan-fuli** [comment]
Thanks for your temporary solution and your effort on G-Audio project, it's realy helpful!!

**Comment by dataflowg** [comment]
New API functions `Set Audio Device Volume.vi` and `Get Audio Device Volume.vi` added to [v0.4.0 release](https://github.com/dataflowg/g-audio/releases/tag/v0.4.0).

**Comment by Ryan-fuli** [comment]
thanks for your update, I can find the setting volumn vi in below folder, but not in labview's quick drop pannel.
C:\Program Files\National Instruments\LabVIEW 2021\vi.lib\Dataflow_G\G-Audio\Audio Devices
![image](https://user-images.githubusercontent.com/80661060/178636062-4399564f-2b9f-41c0-bf0c-401811b24895.png)
