### ISSUE TITLE
Sound recording

### ISSUE THREAD

**Issue by Jamesyang-l** [dataflowg/g-audio#18]
Whether to increase the function of recording sound on the basis of the original, which can help us a lot, thank you

**Comment by dataflowg** [comment]
Hi @Jamesyang-l 

My apologies, I don't quite understand the request. Could you explain a little more about what you're trying to achieve?

**Comment by Jamesyang-l** [comment]
I need to record the sound through your encapsulated driver, similar to the NI tape sound acquisition function 

![12345](https://user-images.githubusercontent.com/52733071/202997987-5eb00f53-47dc-4228-be69-47842598b57e.PNG)

**Comment by dataflowg** [comment]
One of the included example VIs is _Audio Capture Example.vi_, which is similar to NI's sound input example. I've created a similified version that doesn't save to wav. You can download the VI here: [G-Audio Capture Example.vi](https://github.com/dataflowg/snippets/raw/master/G-Audio%20Capture%20Example.vi)

![G-Audio Capture Example](https://user-images.githubusercontent.com/44384905/203451743-72f40f90-4f2b-4d1b-b174-c96d13d8c928.png)

**Comment by Jamesyang-l** [comment]
thankyou
