### ISSUE TITLE
Feature Request: Current Read Position

### ISSUE THREAD

**Issue by ItsMeAshiq** [dataflowg/g-audio#2]
Thankyou for this wonderful Toolkit!!!

I have a suggestion for one improvement.

The **Read Audio File.vim** is able to read the requested amount of samples from the file.
![image](https://user-images.githubusercontent.com/87473267/132179527-874971e1-e961-4efd-a9a7-173454d05557.png)

And we can also change the current offset position to read from, using **Seek Audio File.vi**.
![image](https://user-images.githubusercontent.com/87473267/132179980-f3acc4f3-064e-42fd-bc2b-da85a25a9fd7.png)

So when dynamically changing the Seek position, **Read Audio File.vim** can read the data from that position easily.
But we may not be able to correctly calculate the last read position - ie: the current play time.
![image](https://user-images.githubusercontent.com/87473267/132181534-82040760-e311-4541-aa52-ff187dd1b364.png)

I found a VI inside **Read Audio File.vim** that gives this value, but its in Private Scope.
![image](https://user-images.githubusercontent.com/87473267/132181821-483dbee5-e8b4-4012-935a-2d7a3b2ed84d.png)
![image](https://user-images.githubusercontent.com/87473267/132179352-7bcc21a5-ec38-4f12-b849-b7388cda0012.png)

If you provide the **read_offset** value outside of **Read Audio File.vim**, it would be very useful.

**Comment by dataflowg** [comment]
Hi @ItsMeAshiq, thanks for submitting the (very first) issue.

That's a good suggestion - the value of `read_offset` should be publicly accessible. I'll make it a separate VI, and remove it from `Get Basic Audio File Info` as it's unused there anyway.

**Comment by ItsMeAshiq** [comment]
👍

**Comment by dataflowg** [comment]
`Get Audio File Position.vi` has been added as a public method to `G-Audio.lvlib`. It'll appear in the next release, but if you need it now you can use the package here: [dataflow_g_lib_g_audio-0.2.0.2.vip](https://github.com/dataflowg/g-audio/raw/main/src/LabVIEW/VIPM/dataflow_g_lib_g_audio-0.2.0.2.vip)

**Comment by ItsMeAshiq** [comment]
I think `Get Audio File Position.vi` is only available in the Git Repo. It was not present in the [VI Package - 0.2.0.2](https://github.com/dataflowg/g-audio/raw/main/src/LabVIEW/VIPM/dataflow_g_lib_g_audio-0.2.0.2.vip).

But anyways I hope we can expect it to be available in next release 👍👍.

**Comment by ItsMeAshiq** [comment]
Also check my example repo which demonstrates accessing Audio devices in your PC, at [Audio-Acquisition-Playback](https://github.com/ItsMeAshiq/Audio-Acquisition-Playback).

I have used **`G-Audio`** for implementing audio file playback.

Still there's a room for improvements in accessing Audio devices as your toolkit provides a wide range of access.
But I'll keep that for later right now.

**Comment by dataflowg** [comment]
Hi @ItsMeAshiq - the new function should be available in the Audio Files palette, on the bottom row:
![image](https://user-images.githubusercontent.com/44384905/132777912-5be46366-9483-4e65-b044-51e2cb4edd7d.png)

**Comment by ItsMeAshiq** [comment]
> Hi @ItsMeAshiq - the new function should be available in the Audio Files palette, on the bottom row:

Thanks for the info, and apologies, I was actually checking with version `0.2.0.1` instead of `0.2.0.2`.

**Comment by dataflowg** [comment]
@ItsMeAshiq - FYI both this feature and feature #3 are in the latest release published on VIPM. Thanks again for suggesting them.
